badges = ["travis", "coveralls"]
authority = "cpan:GOCCY"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ['t', 'examples', 'builder']

[FileGatherer]
exclude_match = ['^t/perl/.*', '^example/bigdata.pl']
